#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
    push:
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
    cancel-in-progress: true

jobs:
    duckdb-stable-build:
        name: Build extension binaries
        uses: ./.github/workflows/_extension_distribution.yml
        secrets: inherit
        with:
            duckdb_version: v1.1.3
            ci_tools_version: v1.1.3
            extension_name: bigquery
            exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;osx_amd64;linux_arm64"
            vcpkg_commit: "e01906b2ba7e645a76ee021a19de616edc98d29f"
            extra_toolchains: "parser_tools"

    duckdb-stable-deploy:
        name: Deploy extension binaries
        needs: duckdb-stable-build
        uses: ./.github/workflows/_extension_deploy.yml
        secrets: inherit
        with:
            duckdb_version: v1.1.3
            # ci_tools_version: v1.1.3
            extension_name: bigquery
            exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;osx_amd64;linux_arm64"
            deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
