#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
    push:
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    code-quality-check:
        name: Code Quality Check
        uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@v1.4.1
        with:
            duckdb_version: v1.4.1
            ci_tools_version: v1.4.1
            extension_name: bigquery
            format_checks: "format;tidy"

    duckdb-stable-build:
        name: Build extension binaries
        if: |
            github.event_name == 'pull_request' ||
            (github.event_name == 'push' && github.ref_name == 'main') ||
            (github.event_name == 'push' && github.ref_type == 'tag')
        uses: ./.github/workflows/_extension_distribution.yml
        secrets: inherit
        with:
            extension_name: bigquery
            duckdb_version: v1.4.1
            ci_tools_version: v1.4.1
            exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64_mingw;"
            vcpkg_commit: "ef7dbf94b9198bc58f45951adcf1f041fcbc5ea0"
            extra_toolchains: "parser_tools"
            save_cache: ${{ github.event_name != 'pull_request' }}
            reduced_ci_mode: "disabled"

    duckdb-stable-deploy:
        name: Deploy extension binaries
        needs: duckdb-stable-build
        uses: ./.github/workflows/_extension_deploy.yml
        secrets: inherit
        with:
            extension_name: bigquery
            duckdb_version: v1.4.1
            ci_tools_version: v1.4.1
            exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64_mingw;"
            deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
            reduced_ci_mode: "disabled"
