#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
    push:
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
    cancel-in-progress: true

jobs:
    duckdb-stable-build:
        name: Build extension binaries
        uses: ./.github/workflows/_extension_distribution.yml
        secrets: inherit
        with:
            duckdb_version: v1.0.0
            extension_name: bigquery
            exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;osx_amd64;linux_arm64;linux_amd64_gcc4'
            vcpkg_commit: 'a4275b7eee79fb24ec2e135481ef5fce8b41c339'

    duckdb-stable-deploy:
        name: Deploy extension binaries
        needs: duckdb-stable-build
        uses: ./.github/workflows/_extension_deploy.yml
        secrets: inherit
        with:
            duckdb_version: v1.0.0
            extension_name: bigquery
            exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;osx_amd64;linux_arm64;linux_amd64_gcc4'
            deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
