#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
    push:
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    code-quality-check:
        name: Code Quality Check
        runs-on: ubuntu-22.04
        timeout-minutes: 20
        env:
            CC: gcc-10
            CXX: g++-10
            GEN: ninja
            PIP_DISABLE_PIP_VERSION_CHECK: "1"
            PIP_NO_INPUT: "1"
            PIP_PROGRESS_BAR: "off"
        steps:
            - uses: actions/checkout@v4
              name: Checkout current repository
              with:
                  fetch-depth: 0
                  submodules: "recursive"

            - uses: actions/checkout@v4
              name: Checkout Extension CI tools
              with:
                  path: "extension-ci-tools"
                  ref: v1.5-variegata
                  repository: duckdb/extension-ci-tools

            - name: Install apt format dependencies
              timeout-minutes: 10
              shell: bash
              run: |
                  sudo apt-get -o Acquire::Retries=3 update -y
                  sudo DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::Retries=3 install -y --no-install-recommends ninja-build clang-format-11 python3-venv

            - name: Install Python format dependencies
              timeout-minutes: 10
              shell: bash
              run: |
                  python3 -m venv .format-venv
                  .format-venv/bin/python -m pip install --upgrade pip
                  .format-venv/bin/python -m pip install --timeout 60 --retries 3 cmake-format pyyaml 'black==24.*' cxxheaderparser pcpp 'clang_format==11.0.1'
                  echo "$PWD/.format-venv/bin" >> "$GITHUB_PATH"

            - name: List Installed Packages
              shell: bash
              run: python -m pip freeze

            - name: Format Check
              shell: bash
              run: |
                  clang-format --version
                  clang-format --dump-config
                  black --version
                  make format-check

    duckdb-stable-build:
        name: Build extension binaries
        if: |
            github.event_name == 'pull_request' ||
            (github.event_name == 'push' && github.ref_name == 'main') ||
            (github.event_name == 'push' && github.ref_type == 'tag')
        uses: ./.github/workflows/_extension_distribution.yml
        secrets: inherit
        with:
            extension_name: bigquery
            duckdb_version: v1.5.4
            ci_tools_version: v1.5-variegata
            gcp_environment: ci
            exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64_mingw;"
            vcpkg_commit: "ef7dbf94b9198bc58f45951adcf1f041fcbc5ea0"
            extra_toolchains: "parser_tools"
            save_cache: ${{ github.event_name != 'pull_request' }}
            reduced_ci_mode: "disabled"

    duckdb-stable-deploy:
        name: Deploy extension binaries
        needs: duckdb-stable-build
        uses: ./.github/workflows/_extension_deploy.yml
        secrets: inherit
        with:
            extension_name: bigquery
            duckdb_version: v1.5.4
            ci_tools_version: v1.5-variegata
            gcp_environment: ci
            exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;windows_amd64_mingw;"
            deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
            reduced_ci_mode: "disabled"
